import type { ReviewAnalytics } from './supabase/analytics';

interface ReportData {
  albumTitle: string;
  clientName: string;
  studioName: string;
  ownerName: string;
  phoneNumber: string;
  studioLogoUrl: string;
  totalPages: number;
  reviewedCount: number;
  commentsCount: number;
  voiceCount: number;
  status: string;
  analytics: ReviewAnalytics | null;
}

function formatDate(d: string | null | undefined): string {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

function buildHtml(data: ReportData): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Review Report - ${data.albumTitle}</title>
<style>
  @page { margin: 20mm 15mm; }
  body { font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; color: #1f2937; line-height: 1.5; }
  .header { display: flex; align-items: center; gap: 16px; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 2px solid #e5e7eb; }
  .logo { width: 60px; height: 60px; object-fit: contain; border-radius: 8px; }
  .studio-info h1 { margin: 0; font-size: 22px; }
  .studio-info p { margin: 2px 0 0; color: #6b7280; font-size: 14px; }
  h2 { font-size: 18px; margin: 24px 0 12px; }
  .stats { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 24px; }
  .stat { background: #f3f4f6; border-radius: 8px; padding: 12px 16px; }
  .stat-label { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
  .stat-value { font-size: 24px; font-weight: 700; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
  th { background: #f9fafb; font-weight: 600; color: #374151; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
</style></head>
<body>
  <div class="header">
    ${data.studioLogoUrl ? `<img class="logo" src="${data.studioLogoUrl}" alt="Logo" />` : ''}
    <div class="studio-info">
      <h1>${data.studioName}</h1>
      <p>${data.ownerName ? `${data.ownerName} &middot; ` : ''}${data.phoneNumber || ''}</p>
    </div>
  </div>

  <h2>Review Report: &ldquo;${data.albumTitle}&rdquo;</h2>
  <p style="color:#6b7280;font-size:14px;">Client: ${data.clientName} &middot; Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

  <div class="stats">
    <div class="stat"><div class="stat-label">Total Pages</div><div class="stat-value">${data.totalPages}</div></div>
    <div class="stat"><div class="stat-label">Reviewed</div><div class="stat-value">${data.reviewedCount}</div></div>
    <div class="stat"><div class="stat-label">Comments</div><div class="stat-value">${data.commentsCount}</div></div>
    <div class="stat"><div class="stat-label">Voice Notes</div><div class="stat-value">${data.voiceCount}</div></div>
  </div>

  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>First Opened</td><td>${formatDate(data.analytics?.first_opened_at)}</td></tr>
    <tr><td>Last Viewed</td><td>${formatDate(data.analytics?.last_viewed_at)}</td></tr>
    <tr><td>Pages Viewed</td><td>${data.analytics?.pages_viewed ?? '—'}</td></tr>
    <tr><td>Total Viewing Time</td><td>${data.analytics?.total_viewing_seconds ? `${Math.round(data.analytics.total_viewing_seconds / 60)} min` : '—'}</td></tr>
    <tr><td>Review Submitted</td><td>${formatDate(data.analytics?.review_submitted_at)}</td></tr>
    <tr><td>Approved</td><td>${formatDate(data.analytics?.approved_at)}</td></tr>
  </table>

  <div class="footer">
    Generated by AlbumFlow &middot; ${data.studioName}
  </div>
</body>
</html>`;
}

export function downloadReviewReportHtml(data: ReportData): void {
  const html = buildHtml(data);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${data.albumTitle.replace(/[^a-zA-Z0-9]/g, '_')}_Review_Report.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
